name: "Run Cypress tests"
on: [deployment_status]
jobs:
  e2e:
    environment: Preview
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
          NEXTAUTH_URL: ${{ github.event.deployment_status.target_url }}
          NEXTAUTH_SECRET: ${{ env.DATABASE_URL }}
        with:
          build: npm run build
          start: npm start
